apiVersion: 'skaffold/v2alpha1'
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: restd/multi-translate
      context: .
deploy:
  helm:
    releases:
      - name: multi-translate
        namespace: flum
        chartPath: charts/multi-translate
        values:
          image: restd/multi-translate
        valuesFiles: ["functional_tests/test_values.yaml", "secret_values.yaml"]


portForward:
  - resourceName: multi-translate
    resourceType: Service
    port: 80
    localPort: 8080
    namespace: flum