/*
 * multi-translate
 *
 * Multi-Translate is a unified interface on top of various translate APIs providing optimal translations, persistence, fallback.
 *
 * API version: 0.4.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package multitranslateclient
// HttpValidationError struct for HttpValidationError
type HttpValidationError struct {
	Detail []ValidationError `json:"detail,omitempty"`
}
