/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package multi-translate-client
// HttpValidationError struct for HttpValidationError
type HttpValidationError struct {
	Detail []ValidationError `json:"detail,omitempty"`
}
