/*
 * multi-translate
 *
 * Multi-Translate is a unified interface on top of various translate APIs providing optimal translations, persistence, fallback.
 *
 * API version: 0.5.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package multitranslateclient
// ValidationError struct for ValidationError
type ValidationError struct {
	Loc []string `json:"loc"`
	Msg string `json:"msg"`
	Type string `json:"type"`
}
