/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package multitranslateclient
// ValidationError struct for ValidationError
type ValidationError struct {
	Loc []string `json:"loc"`
	Msg string `json:"msg"`
	Type string `json:"type"`
}
