# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import multi_translate_client
from multi_translate_client.models.translation_response import TranslationResponse  # noqa: E501
from multi_translate_client.rest import ApiException

class TestTranslationResponse(unittest.TestCase):
    """TranslationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TranslationResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = multi_translate_client.models.translation_response.TranslationResponse()  # noqa: E501
        if include_optional :
            return TranslationResponse(
                engine = '0', 
                engine_version = '0', 
                detected_language_confidence = 1.337, 
                from_language = '0', 
                to_language = '0', 
                source_text = '0', 
                translated_text = '0', 
                alignment = [
                    {
                        'key' : {
                            'key' : null
                            }
                        }
                    ]
            )
        else :
            return TranslationResponse(
                engine = '0',
                engine_version = '0',
                from_language = '0',
                to_language = '0',
                source_text = '0',
                translated_text = '0',
        )

    def testTranslationResponse(self):
        """Test TranslationResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
